gcscraper/gcscraper/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('app/admin/', admin.site.urls),
    path('app/', include('main.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gcscraper/main/urls.py
from django.urls import path
from . import views
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView  

app_name = 'main'
admin.site.site_title = 'ゲーム会社スクレーパー' 
admin.site.site_header = 'XXXX' 
admin.site.index_title = 'Menu'

urlpatterns = [
    path('', LoginView.as_view(template_name = 'admin/login.html'), name='login'),
    path('top/', views.Top.as_view(), name="top"),
    path('li/', views.CompanyHomePageList.as_view(), name="page_list"),
    path('g-li/', views.GroupList.as_view(), name="group_list"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('pages/', views.get_all_pages, name = 'get_all_pages'),
    path('add_new_page/', views.add_new_page, name="add_new_page"),
    path('delete_page/', views.delete_page, name="delete_page"),
    path('update_page_field/', views.update_page_field, name="update_page_field"),
    path('update_order/', views.update_order, name = 'update_order'),
    path('add_to_group/', views.add_to_group, name = 'add_to_group'),
    path('add_group_memo/', views.add_group_memo, name = 'add_group_memo'),
    path('update_group_memo/', views.update_group_memo, name = 'update_group_memo'),
    
    path('update_page_order/', views.update_group_order, name="update_group_order"),
    
    path('update_group_page_order/', views.update_group_page_order, name="update_group_page_order"),

    path('delete_from_group/', views.delete_from_group, name = 'delete_from_group'),
    path('add_new_group/', views.add_new_group, name = 'add_new_group'),
    path('update_group_field/', views.update_group_field, name = 'update_group_field'),
    path('delete_group/', views.delete_group, name = 'delete_group')
    
]

gcscraper/main/models.py
from django.db import models

class Group(models.Model):
    name = models.CharField(
        verbose_name = '名前',
        max_length = 100,
        blank = True,
        default = ''
    )
    display_order = models.IntegerField(
        verbose_name = '表示順',
        default = 1,
    )
    memo = models.TextField(
        default = ""
    )


class CompanyHomePage(models.Model):


    page_url = models.URLField(
        verbose_name = "ページURL", 
        max_length=128, 
        blank = True,
        null = True,
        default = ""
    )
    page_html = models.TextField(
        verbose_name = 'html',
        blank = True,
        null = True,
        default = ""
    )

    code = models.CharField(
        verbose_name = 'コード',
        max_length = 100,
        blank = True,
        null = True,
        default = ""
    )
    comment = models.CharField(
        verbose_name = '補足',
        max_length = 255,
        null = True,
        blank = True,
        default = ""
    )
    company_name = models.CharField(
        verbose_name = '会社名',
        max_length = 100,
        blank = True,
        null = True,
        default = ""
    )
    company_name_kana = models.CharField(
        verbose_name = '読み方',
        max_length = 255,
        null = True,
        blank = True,
        default = ""
    )
    market_cap = models.BigIntegerField(
        verbose_name = '時価総額',
        blank = True,
        null = True,
        
    )
    phone_number = models.CharField(
        verbose_name = '電話番号',
        max_length = 50,
        blank = True,
        default = ""
    )
    is_callable = models.BooleanField(
        verbose_name = '電話可能',
        default = False
    )
    display_order = models.IntegerField(
        verbose_name = '表示順',
        default = 1
    )
    memo = models.TextField(
        verbose_name = 'メモ',
        default = ''
    )


class PageGroup(models.Model):
    class Meta:
        ordering = ['display_order']
    group = models.ForeignKey(
        to = Group,
        verbose_name = 'グループ',
        on_delete = models.CASCADE,
        related_name = 'pages',
    )

    page = models.ForeignKey(
        to = CompanyHomePage,
        null = True,
        on_delete = models.CASCADE,
        related_name = 'groups',
    )

    display_order = models.IntegerField(
        verbose_name = '表示順',
        default = 1
    )


class LinkPage(models.Model):
    parent = models.ForeignKey(
        to = CompanyHomePage,
        on_delete = models.CASCADE,
        verbose_name = '親ページ',
        related_name = 'links'
    )
    page_url = models.URLField(
        verbose_name = "ページURL", 
        max_length=128, 
        blank = True,
        null = True,
        default = ""
    )
    page_html = models.TextField(
        verbose_name = 'html',
        blank = True,
        null = True,
        default = ""
    )
    is_scrape_success = models.BooleanField(
        verbose_name = '取得成功',
        default = True
    )

gcscraper/main/views.py
from django.shortcuts import render
from django.views import generic
from .models import *
from django.db.models import F, Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseBadRequest, JsonResponse
import operator
from .serializer import *
import json

class Top(LoginRequiredMixin, generic.TemplateView):
    
    template_name = 'main_top.html'
    def get_context_data(self, **kwargs):
        context = super(Top, self).get_context_data(**kwargs)
        all_included = self.request.GET.get('all_included')
        any_included = self.request.GET.get('any_included')
        
        groups = Group.objects.all()
        

        if all_included:
            q = all_included.split(' ')
            query = reduce(operator.and_, (Q(name__icontains = item) for item in q))
            return groups.filter(query)
            
        elif any_included:
            companies = CompanyHomePage.objects.all()
            satisfy = []
            for company in companies:
                
                q = link_search.split(' ')
                query = reduce(operator.or_, (Q(page_html__icontains = item) for item in q))
                satisfy_links = company.links.filter(query)
                if len(satisfy_links) > 0:
                    satisfy.push(company.pk)
            return CompanyHomePage.objects.filter(pk__in = satisfy)

class CompanyHomePageList(LoginRequiredMixin, generic.ListView):
    model = CompanyHomePage
    template_name = 'main_page_list.html'
    def get_queryset(self):
        qs = CompanyHomePage.objects.all().order_by('display_order')
        return qs


class GroupList(LoginRequiredMixin, generic.ListView):
    model = Group
    template_name = 'main_group_list.html'
    def get_queryset(self):
        qs = Group.objects.all().order_by('display_order')
        return qs

def get_all_pages(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)
    
    if request.method == 'GET':
        qs = CompanyHomePage.objects.all()
        ret_json = PageSerializer(qs, many = True).data
        return JsonResponse(ret_json, safe = False)

def delete_page(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)
    
    if request.method == 'POST':
        CompanyHomePage.objects.get(pk = request.POST.get('pk')).delete()
        return JsonResponse({'success': True})
     
def add_new_page(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)

    if request.method == 'POST':
        new_page = CompanyHomePage()
        
        insert_at = request.POST.get('insert_at')
        after = CompanyHomePage.objects.get(pk = insert_at)
        new_page.display_order = after.display_order + 1
        # update following rows
        CompanyHomePage.objects.filter(display_order__gte = after.display_order + 1).update(display_order = F("display_order") + 1)
        new_page.save()
        data = PageSerializer(new_page, many = False).data
        return JsonResponse(data)

def update_page_field(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)

    if request.method == 'POST':
        
        pk = request.POST.get('pk')
        field_name = request.POST.get('field_name')
        field_value = request.POST.get('field_value')
        if field_value in ('true', 'false'):
            field_value = field_value == 'true'
            print(field_value)

        target = CompanyHomePage.objects.get(pk = pk)
        setattr(target, field_name, field_value)
        target.save()
        return JsonResponse({'success': True})

def update_order(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)

    if request.method == 'POST':
        orderstr = request.POST.get('order_str')
        order_list = orderstr.split(',')
        for i in range(len(order_list)):
            CompanyHomePage.objects.filter(pk = order_list[i]).update(display_order = i + 1)

        return JsonResponse({'success': True})

def update_group_memo(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)

    if request.method == 'POST':
        group_id = request.POST.get('group_id')
        memo = request.POST.get('memo')
        print(memo)

        group = Group.objects.get(pk = group_id)
        group.memo = memo
        group.save()

        return JsonResponse({'success': True})

def update_group_page_order(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)

    if request.method == 'POST':
        group_id = request.POST.get('group_id')
        group = Group.objects.get(pk = group_id)
        new_order = request.POST.get('new_order')
        print(new_order)
        order_list = new_order.split(',')
        for i in range(len(order_list)):
            PageGroup.objects.filter(pk = order_list[i]).update(display_order = i + 1)

        return JsonResponse({'success': True})

def update_group_order(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)

    if request.method == 'POST':
        new_order = request.POST.get('new_order')
        print(new_order)
        order_list = new_order.split(',')
        for i in range(len(order_list)):
            Group.objects.filter(pk = order_list[i]).update(display_order = i + 1)

        return JsonResponse({'success': True})


def add_to_group(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)
    
    if request.method == 'POST':
        group_id = request.POST.get('group_id')
        code = request.POST.get('code')
        if group_id == None or code == None:
            return JsonResponse({'error': True});
        
        try:
            group = Group.objects.get(pk = group_id)
            page = CompanyHomePage.objects.get(code = code)
        except Exception as e:
            print(str(e.args))
            return JsonResponse({'error': str(e.args)})
        
        exist = PageGroup.objects.filter(group = group, page = page)
        if len(exist) > 0:
            print(code)
            return JsonResponse({'error':'既に登録されています'})
        pagegroup = PageGroup(group = group, page = page)
        pagegroup.save()

        data = PageGroupSerializer(pagegroup, many = False).data
        return JsonResponse(data)
        
def add_group_memo(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)
    
    if request.method == 'POST':
        group_id = request.POST.get('group_id')
        memo = request.POST.get('memo')
        if group_id == None or memo == None:
            return JsonResponse({'error': True});
        group = Group.objects.get(pk = group_id)

        pagegroup = PageGroup(group = group, memo = memo, page_or_comment = PageGroupOrMemo.MEMO)
        pagegroup.save()
        

        data = PageGroupSerializer(pagegroup, many = False).data
        return JsonResponse(data)

def delete_from_group(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)
    
    if request.method == 'POST':
        id = request.POST.get('pagegroup_id')
        
        if id == None:
            print('no parma')
            return JsonResponse({'error': True});
        
        try:
            page_or_memo = PageGroup.objects.get(pk = id)
            page_or_memo.delete()
        except Exception as e:
            print(str(e.args))
            return JsonResponse({'error': str(e.args)})
        
        return JsonResponse({'success': True})

def delete_group(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)
    
    if request.method == 'POST':
        id = request.POST.get('group_id')
    
        Group.objects.get(pk = id).delete()
        return JsonResponse({'success': True})

def add_new_group(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)
    
    if request.method == 'POST':
        after = Group.objects.get(pk = request.POST.get('after'))
        
        new_group = Group(display_order = after.display_order + 1)
        new_group.save()

        Group.objects.filter(display_order__gte = after.display_order + 1).update(display_order = F("display_order") + 1)

        data = GroupSerializer(new_group, many = False).data        
        return JsonResponse(data)

def update_group_field(request):
    if request.user.is_anonymous or request.user.is_active == False:
        return JsonResponse({'error' : 'authentication failed'}, status=401)

    if request.method == 'POST':
        
        group_id = request.POST.get('group_id')
        field_name = request.POST.get('field_name')
        field_value = request.POST.get('field_value')

        if field_value in ('true', 'false'):
            field_value = field_value == 'true'
            

        target = Group.objects.get(pk = group_id)
        setattr(target, field_name, field_value)
        target.save()
        return JsonResponse({'success': True})

gcscraper/main/templates/main_base.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
 
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- jQuery UI -->
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">      
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/functions.js' %}"></script>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    {% block style %}
    {% endblock %}
    <title>XXXX</title>
</head>
<body>
<!-- Image and text -->
<style>
  .my-page-title {
    background-color: lightblue
  }
</style>

<nav class="navbar navbar-expand-md bg-light navbar-light sticky-top">
        <a class="navbar-brand" href="#">XXXX</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb" aria-expanded="true">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navb" class="navbar-collapse collapse hide">
          <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'main:top' %}">検索</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:page_list' %}">HP一覧</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:group_list' %}">グループ一覧</a>
              </li>  
          </ul>
      
          <ul class="nav navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <span class="nav-link"><span class="fas fa-user"></span> {{ user.username }} さん</span>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:logout' %}"><i class="fas fa-sign-out-alt"></i> Log out</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:login' %}"><span class="fas fa-sign-in-alt"></span> Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    <div class="container">
      <h2 class="text-center my-page-title">
          {% block title %}{% endblock %} 
      </h2>
    </div>
    <!-- メインコンテント -->
    <div class="container text-center">
        {% block content %}{% endblock %}
    </div>
    <script>
      const UPDATE_PAGE_ORDER = "{% url 'main:update_order' %}";
      const ADD_NEW_PAGE = "{% url 'main:add_new_page' %}";
      const DELETE_PAGE = "{% url 'main:delete_page' %}";
      const UPDATE_PAGE_FIELD = "{% url 'main:update_page_field' %}";
      const GET_ALL_PAGES = "{% url 'main:get_all_pages' %}";
      const ADD_TO_GROUP = "{% url 'main:add_to_group' %}";      
      const DELETE_FROM_GROUP = "{% url 'main:delete_from_group' %}";
      const UPDATE_PAGEGROUP_ORDER = "{% url 'main:update_group_page_order' %}";
      const UPDATE_GROUP_ORDER = "{% url 'main:update_group_order' %}";
      const UPDATE_GROUP_MEMO = "{% url 'main:update_group_memo' %}";
      const ADD_NEW_GROUP = "{% url 'main:add_new_group' %}";
      const DELETE_GROUP = "{% url 'main:delete_group' %}";
      const UPDATE_GROUP_FIELD = "{% url 'main:update_group_field' %}";
      

      function getCookie(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              var cookies = document.cookie.split(';');
              for (var i = 0; i < cookies.length; i++) {
                  var cookie = jQuery.trim(cookies[i]);
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }

      var csrftoken = getCookie('csrftoken');

      function csrfSafeMethod(method) {
          // these HTTP methods do not require CSRF protection
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
      }

      $.ajaxSetup({
          beforeSend: function (xhr, settings) {
              if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                  xhr.setRequestHeader("X-CSRFToken", csrftoken);
              }
          }
      });
    </script>
    {% block extra_js %}{% endblock %}
</body>
</html>

gcscraper/main/templates/main_top.html
{% extends 'main_base.html' %}

{% block style %}
    <style>
        input.search {
            width: 100%
        }
        input[type="submit"] {
            margin: 2rem 0;
        }
        input:read-only {
            border:none;
            background-color: transparent;
            color: gray;
        }
        a {
            font-size: 14px!important;
            margin: 1.7rem 0
        }
        form {
            text-align: left
        }
        div.container {
            padding: 0!important;
            max-width: 98%;  
           
        }
        .new_page_form input {
            width: 100%
        }

        
    </style>
{% endblock %}

{% block title %}
検索
{% endblock %}

{% block content %}

<div class="row">
    <div class="col-2 left-pane">
        <form id="id_search_form" method="GET" action="#">
            <label for="id_all_included">キーワードを全て含む</label><br>
            <input id="id_all_included" type="text" class="search" name="all_included"><br>
          
            <label for="id_any_included">キーワードいづれかを含む</label><br>
            <input id="id_any_included" type="text" class="search" name="any_included"><br>
            <input type="submit" value="検索実行">
        </form>
    </div>
    <div class="col-1">
        <a href="{% url 'main:group_list' %}" class="btn btn-primary btn-block">グループ一覧</a>
        <a href="{% url 'main:page_list' %}" class="btn btn-primary btn-block">HP登録会社一覧</a>
    </div>
    <div class="col-9">
        <form id="id_register_form" class="new_page_form">
            <div class="row">
                <div class="col-2">
                    <label for="id_code">コード</label>
                    <input id="id_code" type="text" name="code">
                </div>
                <div class="col-2">
                    <label for="id_company_name">補足</label>
                    <input id="id_comment" type="text" name="comment">
           
                </div>
                <div class="col-2">
                    <label for="id_company_name_kana">会社名</label>
                    <input id="id_company_name" type="text" name="company_name">
            
                </div>
                <div class="col-2">
                    <label for="id_company_name_kana">読み方</label>
                    <input id="id_company_name_kana" type="text" name="company_name_kana">
            
                </div>
                <div class="col-2">
                    <label for="id_phone_number">電話番号</label>
                    <input id="id_phone_number" type="text" name="phone_number">
            
                </div>
                <div class="col-2">
                    <label for="id_is_callable">電話可能</label>
                    <input id="id_is_callable" type="checkbox" name="is_callable">
            
                </div>
                <div class="col-2">
                    <label for="id_hp_url">HPのトップページ</label>
                    <input id="id_hp_url" type="text" name="hp_url">
                </div>
                <div class="col-1">
                        <input type="submit" value="登録">
                </div>                                                              
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block extra_js %}
    <script>
        $(function() {

        });
    
    
    </script>

{% endblock %}